### ISSUE TITLE
Does this work with Django 1.8.2

### ISSUE THREAD

**Issue by Jzarecta** [omab/django-social-auth#833]
Wonder if anyone have tried this plugin on Django 1.8.2 succesfully.

**Comment by mrigdon-zz** [comment]
+1

**Comment by Tatsh** [comment]
It seems to work, but there are some warnings and you have to enable the non-secure `PickleSerializer` as your `SESSION_SERIALIZER` (default for a while has been the JSON serialiser). If you do not, Facebook login will not work.

```
/home/tatsh/.virtualenvs/fos/lib/python2.7/site-packages/social_auth/utils.py:14: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  from django.db.models.loading import get_model

/home/tatsh/.virtualenvs/fos/lib/python2.7/site-packages/social_auth/models.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module
```

**Comment by evcb** [comment]
Yes. I implemented on 1.9 with no problem.

**Comment by vasylnakvasiuk** [comment]
@hellvix @Tatsh 

Python 3.5.0
Django 1.9.1
django-social-auth 0.7.28

During "migrate" or "runserver" I got:

```
from django.utils.importlib import import_module
ImportError: No module named 'django.utils.importlib'
```

Changing SESSION_SERIALIZER didn't solve my problem.

**Comment by evcb** [comment]
@vaxXxa django-social-auth is no longer in use. You should install `python-social-auth` (https://github.com/omab/python-social-auth).

**Comment by vasylnakvasiuk** [comment]
@hellvix ok.. thnx

**Comment by Andrii-D** [comment]
@hellvix How hard is to migrate from `django-social-auth` to `python-social-auth`? 
If there is any guidelines of how to do it?
Thanks!

**Comment by evcb** [comment]
There is no documentation on how to the migration but the API is pretty
much the same. Just take a look in the documentation that you'll be able to
make the proper changes.

Den 14. jun. 2016 12.00 skrev "Andrii Dvoiak" notifications@github.com:
